# -*- coding: utf-8 -*-
"""Calculadora_inteligente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpKZmcLV-wm2qIH8LLZSlP7bT1iwI3mT

**Calculadora Inteligente**
"""

# Usuário digita ao menos 2 números.

num1 = int(input('Digite o primeiro número: '))
num2 = int(input('Digite o segundo número: '))

# Implemente ao menos 4 operações matemáticas.

print('1. Soma')
print('2. Subtração')
print('3. Multiplicação')
print('4. Divisão')

# Usuário escolhe qual operação matemática deseja fazer.

operacao = input('Escolha uma operação matemática (1,2,3 ou 4)')

if operacao == '1':
  print('Você escolheu a operação de soma')
elif operacao == '2':
  print('Você escolheu a operação de subtração')
elif operacao == '3':
  print('Você escolheu a operação de multiplicação')
elif operacao == '4':
  print('Você escolheu a operação de divisão')
else:
  print('Operação inválida')


# Operações matemáticas + condicional.

if operacao == '1':
  resultado = num1 + num2
  print('O resultado da soma é: ', resultado)
elif operacao == '2':
  resultado = num1 - num2
  print('O resultado da subtração é: ', resultado)
elif operacao == '3':
  resultado = num1 * num2
  print('O resultado da multiplicação é: ', resultado)
elif operacao == '4':
  resultado = num1 / num2
  print('O resultado da divisão é: ', resultado)
else:
  print('Operação inválida. Tente novamente.')